wallpaper {
        monitor = eDP-1
        path = /home/nyashka/.config/wallpapers/08e5df4fc1be18157b0b3e4c78.jpg
        fit_mode = cover
}
wallpaper {
	monitor = HDMI-A-1
	path = /home/nyashka/.config/wallpapers/08e5df4fc1be18157b0b3e4c78.jpg
	fit_mode = cover
}

splash=false
