wallpaper {
        monitor = eDP-1
        path = /home/nyashka/.config/wallpapers/387a4d0b67bcc93ced6d7891bacc4c70.jpg
        fit_mode = cover
}
wallpaper {
	monitor = HDMI-A-1
	path = /home/nyashka/.config/wallpapers/387a4d0b67bcc93ced6d7891bacc4c70.jpg
	fit_mode = cover
}

splash=false
