wallpaper {
        monitor = eDP-1
        path = /home/nyashka/.config/wallpapers/HOx9rBDbIAAysLQ.jpg
        fit_mode = cover
}
wallpaper {
	monitor = HDMI-A-1
	path = /home/nyashka/.config/wallpapers/HOx9rBDbIAAysLQ.jpg
	fit_mode = cover
}

splash=false
